# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96d9054bf4ee342709573e605f8b2d56"
name = "Inventorify-Staging"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["inventory_levels/update"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

[access_scopes]
scopes = "write_products,read_orders,read_inventory"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com"
subpath = "inventorify-staging"
prefix = "apps"